name: Test

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    publish-tauri:
        permissions:
            contents: write

        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create fake exe
              run: |
                  mkdir dir
                  echo hi > dir\hello.exe
              shell: pwsh
            - name: Upload installer
              run: |
                  bun scripts/publish.js dir/*.exe
              shell: pwsh
